language: node_js
node_js: 16
jobs:
  include:
  - stage: test
    script:
    - yarn build
    - yarn test
before_deploy:
  - yarn build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: main