language: node_js
node_js: 16
jobs:
  include:
  - stage: test
    script:
    - yarn build
    - yarn test
deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      branch: main
  - provider: npm
    tag: beta
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      branch: beta